name: Debug chaos python error

on:
  workflow_dispatch:
jobs:
  
  test-cluster-n-node-chaos: 
    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    
    steps:
      
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependency
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: error
          shell: bash
          command: |
            pip install -r tests/python_client/deploy/requirements.txt
            pip list | grep protobuf
            pip install --upgrade protobuf   
            pip list | grep protobuf
             

      