name: Pull Request Action 
on:  
  pull_request:
    paths:
      - 'scripts/**'
      - 'internal/**'
      - 'cmd/**'
      - 'build/**'
      - '.github/workflows/code-checker.yaml'
      - '.env'
      - docker-compose.yml
      - Makefile
      - '!**.md'
      - '!build/ci/jenkins/**'
      # FIXME(wxyu): not need to run code check, update the ci-passed rules and remove these two lines
      - go.mod
      - go.sum
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v1
    - name: GoGitOps Step  
      id: gogitops  
      uses: beaujr/gogitops-action@v0.2
      with:  
        github-actions-token: ${{secrets.GITHUB_TOKEN}}