name: Jenkins Checker
# Lint Jenkinsfile  and related groovy files

on:
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'build/ci/jenkins/**'

jobs:
  ubuntu:
    name: Jenkins Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    